// <auto-generated />
using System;
using LaliWebShop.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaliWebShop.Api.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20221203232345_Warenkorb2")]
    partial class Warenkorb2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LaliWebShop.Api.Entities.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Artikelnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BestellungId")
                        .HasColumnType("int");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("KategorieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PreisSingleNetto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Artikel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artikelnummer = "K1",
                            Bezeichnung = "A kit provided by Glossier, containing skin care, hair care and makeup products",
                            ImageURL = "/ArtikelImages/Kleidung/Kleider.png",
                            KategorieId = 1,
                            KategorieName = "Kleidunghgggg",
                            Menge = 100,
                            Name = "TestKleidung",
                            PreisSingleNetto = 100m
                        },
                        new
                        {
                            Id = 2,
                            Artikelnummer = "H1",
                            Bezeichnung = "A kit provided by Glossier, containing skin care, hair care and makeup products",
                            ImageURL = "/ArtikelImages/Haushaltgeräte/HaushaltGerät.png",
                            KategorieId = 2,
                            KategorieName = "Haushaltgeräte",
                            Menge = 100,
                            Name = "HaushaltgeräteTest",
                            PreisSingleNetto = 100m
                        },
                        new
                        {
                            Id = 3,
                            Artikelnummer = "E1",
                            Bezeichnung = "A kit provided by Glossier, containing skin care, hair care and makeup products",
                            ImageURL = "/ArtikelImages/Elektronikgeräte/ElekGerät.png",
                            KategorieId = 3,
                            KategorieName = "Elektronikgeräte",
                            Menge = 100,
                            Name = " ElektronikgeräteTest",
                            PreisSingleNetto = 100m
                        },
                        new
                        {
                            Id = 4,
                            Artikelnummer = "C1",
                            Bezeichnung = "A kit provided by Glossier, containing skin care, hair care and makeup products",
                            ImageURL = "/ArtikelImages/Computer/Computer.png",
                            KategorieId = 4,
                            KategorieName = "Computer",
                            Menge = 100,
                            Name = "ComputerTest",
                            PreisSingleNetto = 100m
                        },
                        new
                        {
                            Id = 5,
                            Artikelnummer = "M1",
                            Bezeichnung = "A kit provided by Glossier, containing skin care, hair care and makeup products",
                            ImageURL = "/ArtikelImages/Mobiletelefone/Mobile.png",
                            KategorieId = 5,
                            KategorieName = "Mobiletelefone",
                            Menge = 100,
                            Name = "MobiletelefoneTest",
                            PreisSingleNetto = 100m
                        },
                        new
                        {
                            Id = 6,
                            Artikelnummer = "T1",
                            Bezeichnung = "A kit provided by Glossier, containing skin care, hair care and makeup products",
                            ImageURL = "/ArtikelImages/TestKategorie/Test.png",
                            KategorieId = 6,
                            KategorieName = "TestKategorie",
                            Menge = 100,
                            Name = "TestKategorieTest",
                            PreisSingleNetto = 100m
                        });
                });

            modelBuilder.Entity("LaliWebShop.Api.Entities.Bestellung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BestellNummer")
                        .HasColumnType("int");

                    b.Property<DateTime>("BestelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("KundenId")
                        .HasColumnType("int");

                    b.Property<decimal>("MwSt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SummeBrutto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SummeNetto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Bestellung");
                });

            modelBuilder.Entity("LaliWebShop.Api.Entities.BestellungsArtikel", b =>
                {
                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<int>("BestellungId")
                        .HasColumnType("int");

                    b.Property<int>("ArtikelMenge")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ArtikelId", "BestellungId");

                    b.HasIndex("BestellungId");

                    b.ToTable("BestellungsArtikel");
                });

            modelBuilder.Entity("LaliWebShop.Api.Entities.Kategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kleidung"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Haushaltgeräte"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Elektronikgeräte"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mobiletelefone"
                        },
                        new
                        {
                            Id = 6,
                            Name = "TestKategorie"
                        });
                });

            modelBuilder.Entity("LaliWebShop.Api.Entities.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Anrede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hausnummer")
                        .HasColumnType("int");

                    b.Property<int>("KundenNummer")
                        .HasColumnType("int");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plz")
                        .HasColumnType("int");

                    b.Property<string>("Strasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kunde");
                });

            modelBuilder.Entity("LaliWebShop.Api.Entities.Warenkorb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BestellungId")
                        .HasColumnType("int");

                    b.Property<int>("KundenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Warenkorb");
                });

            modelBuilder.Entity("LaliWebShop.Api.Entities.BestellungsArtikel", b =>
                {
                    b.HasOne("LaliWebShop.Api.Entities.Artikel", "Artikel")
                        .WithMany("BestellungsArtikel")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaliWebShop.Api.Entities.Bestellung", "Bestellung")
                        .WithMany("BestellungsArtikel")
                        .HasForeignKey("BestellungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Bestellung");
                });

            modelBuilder.Entity("LaliWebShop.Api.Entities.Artikel", b =>
                {
                    b.Navigation("BestellungsArtikel");
                });

            modelBuilder.Entity("LaliWebShop.Api.Entities.Bestellung", b =>
                {
                    b.Navigation("BestellungsArtikel");
                });
#pragma warning restore 612, 618
        }
    }
}
